In [9]:
import numpy as np

load = np.load("p-1-train.npz")
X = load["X"]
Y = load["Y"]
np.shape(X)

(40000, 2)

In [3]:
X

array([[-1.1652832 , -0.8649874 ],
       [-1.2063147 ,  0.04685342],
       [-1.1559672 ,  0.9569603 ],
       ...,
       [-0.2856088 ,  0.89221853],
       [-0.1840857 ,  1.1222024 ],
       [-0.06477205,  1.2448609 ]], dtype=float32)

In [7]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler(feature_range=(-1, 1))
nX = scaler.fit_transform(X)
nX

array([[-0.7960221 , -0.20652299],
       [-0.8240603 ,  0.01130301],
       [-0.78965616,  0.22871481],
       ...,
       [-0.1949101 ,  0.21324891],
       [-0.12553583,  0.26818883],
       [-0.04400469,  0.2974902 ]], dtype=float32)

In [10]:
Y

array([[-1.2063147 ,  0.04685342],
       [-1.1559672 ,  0.9569603 ],
       [-1.0162134 ,  1.8274915 ],
       ...,
       [-0.1840857 ,  1.1222024 ],
       [-0.06477205,  1.2448609 ],
       [-0.06477205,  1.2448609 ]], dtype=float32)